Dockeres javítások
joladnijo/joladnijo-backend pull request #25
Opened 2022-03-11 10:00 UTC by nvi9

2022-03-11 11:07 UTC, molnarbence commented
Ilyen PR-ok johetnek barmikor. Frontendre is. Koszi 👍

2022-03-11 11:11 UTC, molnarbence commented on joladnijo/settings.py
> +        'USER': os.environ.get('DBUSER', 'svc_backend'),
Jo otlet lenne a service user es az adatbazis nevenek felulirasara kulonbozo kornyezetekben? A usernev felulirasat akkor latnam szuksegesnek, ha pl. a migration scripthez egy super usert hasznalnank, ami tudja modositani az adatbazis strukturat, a sima webservice futtatashoz pedig maradna a service user, ami csak INSERT, UPDATE, SELECT, DELETE-t tud futtatni.
Az adatbazis nevet viszont hagynam igy minden kornyezetben.

2022-03-11 11:19 UTC, nvi9 commented on joladnijo/settings.py
> +        'USER': os.environ.get('DBUSER', 'svc_backend'),
Oké, visszaállítottam. Viszont akkor nem kell a docker-compose fájlokba sem a környezeti változó ezekhez.

2022-03-11 11:23 UTC, molnarbence commented on joladnijo/settings.py
> +        'USER': os.environ.get('DBUSER', 'svc_backend'),
Igen, azokra sem lesz akkor szukseg.

2022-03-13 16:17 UTC, molnarbence commented on docker-compose.prod.yml
> +      MYSQL_USER: svc_backend
Erre mar nincs szukseg.

2022-03-13 16:17 UTC, molnarbence commented on docker-compose.prod.yml
> +      MYSQL_DATABASE: joladnijo
Erre sem

2022-03-14 14:42 UTC, edeak submitted a review, later dismissed

2022-03-14 18:39 UTC, molnarbence approved these changes
LGTM

2022-03-15 09:45 UTC, molnarbence requested changes
`docker-compose up`-nal `Permission denied` uzenet erkezik. Nincs jogosultsaga futtatni a `./start-django.sh`-t

2022-03-15 09:54 UTC, merged

2022-03-15 10:23 UTC, nvi9 commented
> `docker-compose up`-nal `Permission denied` uzenet erkezik. Nincs jogosultsaga futtatni a `./start-django.sh`-t

Ha Windowson vagy, akkor át kell állítani az újsor karaktert LF-re, úgy elvileg mennie kell.

2022-03-15 10:26 UTC, molnarbence commented
> 
Ubuntun futtattam. Ha ubuntun elotte adok futasi jogosultsagot `chmod +x ./start-django.sh`, akkor aztan megy a build.