PoC: Endpointok FE elérés teszteléséhez
joladnijo/joladnijo-backend pull request #26
Opened 2022-03-11 17:23 UTC by nvi9

Az alábbi új URL-eken lehet tesztelni az elérést frontendről. A `localhost:8000` cserélendő nem localhostos környezet esetén.

- `localhost:8000/test`

  Válasz:
  ```json
  {"success": true, "message": "OK", "djangoVersion": [3, 2, 0, "final", 0]}
  ```
  HTTP státuszkód: `200`

- `localhost:8000/test/valami`

  Válasz:
  ```json
  {"success": true, "message": "OK", "djangoVersion": [3, 2, 0, "final", 0], "slug": "valami"}
  ```
  HTTP státuszkód: `200`

- `localhost:8000/test/400`

  Válasz:
  ```json
  {"success": false, "message": "Bad request"}
  ```
  HTTP státuszkód: `400`

- `localhost:8000/test/403`

  Válasz:
  ```json
  {"success": false, "message": "Permission denied"}
  ```
  HTTP státuszkód: `403`

- `localhost:8000/test/404`

  Válasz:
  ```json
  {"success": false, "message": "Not found"}
  ```
  HTTP státuszkód: `404`

- `localhost:8000/test/500`

  Válasz:
  ```json
  {"success": false, "message": "Server error"}
  ```
  HTTP státuszkód: `500`

2022-03-11 17:25 UTC, molnarbence approved these changes
LGTM

2022-03-11 17:28 UTC, nvi9 commented
> LGTM

Még kérni sem volt időm a review-t ⚡

2022-03-13 15:22 UTC, molnarbence submitted a review, later dismissed

2022-03-13 18:17 UTC, molnarbence commented
Kene meg engedelyezni a CORS hivasokat a frontendrol, mert lokal tesztnel kulonbozo lesz az origin, mert a backend a 8000-es porton, a frontend a 3000-es porton fog futni.

2022-03-14 14:43 UTC, edeak submitted a review, later dismissed

2022-03-14 15:43 UTC, molnarbence requested changes
Frontenddel tesztelve CORS problemak merultek fel. A backenden be kellene allitani egy olyan CORS policy-t, ami a kovetkezo origineket engedelyezi:
- http://localhost:8000
- https://staging.joladnijo.jmsz.hu
- https://joladnijo.jmsz.hu

2022-03-14 17:37 UTC, nvi9 commented
> https://github.com/adamchainz/django-cors-headers

Ezt mindjárt beállítom, ha más még nem kezdett neki.

2022-03-15 12:36 UTC, nvi9 commented
Feloldottam a merge conflictokat, de lehet, hogy megint kell majd egy `chmod` a start-django.sh-ra...

2022-03-15 16:53 UTC, molnarbence commented on joladnijo/settings.py
> +    'http://localhost:8000',
Ezt elneztem elsore. Lokalban a frontend a 3000-es porton fog futni. A backend fut a 8000-es porton
```suggestion
    'http://localhost:3000',
```

2022-03-15 17:07 UTC, molnarbence approved these changes
LGTM.

2022-03-15 17:07 UTC, molnarbence commented
Teszteltem lokalban a frontenddel.

2022-03-15 17:07 UTC, merged